### PR TITLE
Exposed download status of the map

### PR DESCRIPTION
**Pull request by Mangatome**
StaticMap.Status and StaticMap.StatusChanged can now be used to
determine if the map was succesfully downloaded or not.
Allows users to solve #7 at will.

### CODE REVIEW

**Comment by Mangatome** [comment]
@jeffwilcox Any chance to merge and update Nuget packages to help integrating the fix in other open-source projects? :)

**Comment by jeffwilcox** [comment]
Let me get on this! Thank you for submitting.

**Comment by Mangatome** [comment]
Thanks a lot :)

**Comment by jeffwilcox** [comment]
Just booting a VM with the older VS to make some minor nits, update the NuSpec version and then build. Should be updated later today.

To be honest, I don't have a lot of easy ways to validate this set of changes on my end, and no unit tests, so I'd appreciate it if you could incorporate and share any feedback after the update!

Thanks so much. I'll also update the contributors list on the NuGet package to include you. Cheers and happy new year.

**Comment by Mangatome** [comment]
Sure will, thanks. Happy new year!

**Pull request merged**
